# Generated by Django 5.0.3 on 2024-03-25 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_exercisetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoals',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencepoints',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
