# Generated by Django 5.0.3 on 2024-03-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_dailygoals_date_experiencepoints_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
