# Generated by Django 4.2.10 on 2024-04-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_delete_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseType',
        ),
    ]
